### ISSUE TITLE
Barra superior fondos

### ISSUE THREAD

**Issue by pezestudio** [montera34/pezestudio-theme#18]
Nos parece mejor solución que las categorías de la barra superior sean sólidas y de un color que contraste con el fondo y que no tengan el sombreado. Igual los logos de FB y TW, sólidos y sin sombra. Y cuando estás dentro de una categoría que siga cambiando de color.

**Comment by skotperez** [comment]
Cierro este issue. Repetido: https://github.com/montera34/pezestudio-theme/issues/8
